BruteForce : 14697_방배정하기 - CMS
psjcc/algo pull request #13
Opened 2023-08-03 08:21 UTC by thingseong

해줘

2023-08-04 02:29 UTC, cJinu requested changes

2023-08-04 02:29 UTC, cJinu commented on src/BruteForce/CMS/BOJ_14697_방배정하기.java
> +		}
한번에 탈출해조요

2023-08-04 07:37 UTC, thingseong commented on src/BruteForce/CMS/BOJ_14697_방배정하기.java
> +		}
유감

2023-08-04 07:37 UTC, thingseong commented on src/BruteForce/CMS/BOJ_14697_방배정하기.java
> +		}
loop 애용하겠습니다.
![image](https://github.com/psjcc/algo/assets/72279836/87e2876e-ada2-4934-9898-668291af87c8)

2023-08-04 07:38 UTC, merged

2023-08-06 05:01 UTC, thingseong commented on src/BruteForce/CMS/BOJ_14697_방배정하기.java
> +		}
asd